### ISSUE TITLE
Handling CSV files that are semi-colon delimited

### ISSUE THREAD

**Issue by nilskoll** [miyako/4d-component-csv#1]
Many CSV-files are semi-colon delimited, not comma-delimited.
I added an optional "delimiter" parameter to the params object to handle semi-colon.
Also, if the file contains a line with an incorrectly escaped double-quote inside a column, the parsing stops at that line ignoring the rest of the file. I added an optional "skip_errors" boolean parameter to allow the parsing of the rest of the file.
[CSV_TO_TEXT_MATRIX.txt](https://github.com/miyako/4d-component-csv/files/1308485/CSV_TO_TEXT_MATRIX.txt)

**Comment by miyako** [comment]
thank you, I've updated the method
